exports.BAD_REQUEST = 400;
exports.UNAUTHORIZED_STATUS_CODE = 401;
exports.RESOURCE_NOT_FOUND_STATUS_CODE = 404;
exports.OK_STATUS_CODE = 200;
exports.RESOURCE_ALREADY_EXISTS_STATUS_CODE = 409;

exports.DEFAULT_LIST_POSTS_LIMIT = 50;
exports.DEFAULT_LIST_COMMENTS_LIMIT = 30;
exports.DEFAULT_LIST_NOTIFICATIONS_LIMIT = 30;
exports.DEFAULT_LIST_FOLLOWERS_LIMIT = 30;
exports.DEFAULT_LIST_FOLLOWING_LIMIT = 30;

exports.IMAGE_KEY = 'image';
exports.EXPRESS_STATIC_PATH = 'public';

exports.POSTS_API_CONTROLLER_LOG_GROUP = 'posts-api-controller';
