name: Instagram Clone CI
on:
  pull_request:
    branches:
      - main
jobs:
  server-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'

      - name: Run tests
        run: npm test
        working-directory: ./server
