yaml
name: Instagram Clone CI
on:
  pull_request:
    branches:
      - main
jobs:
  development:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Unit tests
      run: npm test